import Head from "next/head";
import { motion, useScroll, useSpring, useTransform } from "framer-motion";

import { useRef } from "react";


function Section({ children }) {
  const ref = useRef(null);

  return (
    <div className="">
      <section className="h-fit" ref={ref}>
        <motion.span>{children}</motion.span>
      </section>
    </div>
  );
}

const variants = {
  initial: { opacity: 0, y: -20 },
  inView: { opacity: 1, y: 0 },
  transition: { duration: 3 },
};

export default function Home() {
  const { scrollYProgress } = useScroll();

  const y_header_text = useSpring(useTransform(scrollYProgress, [0, 1], [0, 400]));
  const header_orange = useTransform(scrollYProgress, [0, 1], [0, 500]);
  const header_red = useTransform(scrollYProgress, [0, 1], [0, 200]);
  const header_red_scale = useTransform(scrollYProgress,[0,1],[1,10])
  const header_yellow = useTransform(scrollYProgress, [0, 1], [0, 100]);
  const header_fade = useTransform(scrollYProgress,[0,0.5],[1,0])
  const default_variants = {
    visible: { opacity: 1, y: 0 },
    hidden: { opacity: 0, y: -100 },
  };

  return (
    <>
      <Head>
        <title>ARD. Web Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="header-container">
          <motion.img style={{opacity:header_fade}} src="/ard_bg.jpg" />

          <Section>
            <motion.img
              src="/header_text.png"
              initial="hidden"
              animate="visible"
              transition={{ duration: 0.7 }}
              variants={default_variants}
              style={{ y: y_header_text }}
              className="header-text text-7xl font-black"
            />
          </Section>


          {/* header circles */}

          <motion.svg 
          className="header-orange w-64 " 
          style={{ y: header_orange }}
              initial="hidden"
              animate="visible"
              transition={{ duration: 1.4 }}
              variants={default_variants}
          viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
            <circle cx="50" cy="50" r="50" fill="#F37748" />
          </motion.svg>


          <motion.svg 
          className="header-red w-20"
          style={{ y: header_red,scale:header_red_scale }}
          initial="hidden"
              animate="visible"
              transition={{ duration: 1 }}
              variants={default_variants}
          viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
            <circle cx="50" cy="50" r="50" fill="#B42D2F" />
          </motion.svg>

          <motion.svg 
          className="header-yellow w-20"
          style={{y:header_yellow,scale:header_red_scale}}
          initial="hidden"
              animate="visible"
              transition={{ duration: 0.7 }}
              variants={default_variants}
          viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
            <circle cx="50" cy="50" r="7" fill="#FED766" />
          </motion.svg>
          </div>

        
        <div className="h-screen "></div>
        <div className="h-screen"></div>
      </main>
    </>
  );
}
{
  /* <motion.h1
                   initial={"initial"}
                   whileInView={"inView"}
                   variants={variants}
                   transition={{duration:1}}
       className='header-text text-7xl font-black'>
        ARD.
        </motion.h1> */
}
